openapi: 3.0.3
info:
  title: OpenAPI schema for template terraform-aws-msk-kafka
components:
  schemas:
    variables:
      type: object
      required:
      - infrastructure
      properties:
        infrastructure:
          title: Infrastructure
          type: object
          description: |
            Specify the infrastructure information for deploying.
          required:
          - vpc_id
          properties:
            kms_key_id:
              description: |
                The KMS key id for the kafka cluster.
              title: Kms Key Id
              type: string
              x-walrus-ui:
                order: 2
            vpc_id:
              description: |
                The VPC ID for the kafka cluster.
              title: Vpc Id
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 2
        broker_per_zone:
          title: Broker Per Zone
          type: number
          description: |
            The desired number of broker nodes per zone in the kafka cluster.
          default: 1
          x-walrus-ui:
            group: Basic
            order: 3
        engine_version:
          title: Engine Version
          type: string
          description: |
            Specify the deployment engine version, select from https://docs.aws.amazon.com/msk/latest/developerguide/supported-kafka-versions.html.
          default: 3.6.0
          x-walrus-ui:
            group: Basic
            order: 4
        engine_parameters:
          title: Engine Parameters
          type: array
          description: |
            Specify the deployment engine parameters, select for https://docs.aws.amazon.com/msk/latest/developerguide/msk-configuration-properties.html.
          default: []
          items:
            properties:
              name:
                title: Name
                type: string
                x-walrus-ui:
                  order: 1
              value:
                title: Value
                type: string
                x-walrus-ui:
                  order: 2
            required:
            - name
            - value
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        sasl_authentication:
          title: Sasl Authentication
          type: object
          description: |
            Specify the SASL authentication information for the Kafka service.
          default:
            iam: false
            scram: false
          properties:
            iam:
              default: false
              description: |
                Enable IAM authentication for the kafka cluster.
              title: Iam
              type: boolean
              x-walrus-ui:
                order: 2
            scram:
              default: false
              description: |
                Enable SCRAM authentication for the kafka cluster.
              title: Scram
              type: boolean
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
        resources:
          title: Resources
          type: object
          description: |
            Specify the computing resources.
          default:
            class: kafka.t3.small
          properties:
            class:
              default: kafka.t3.small
              description: |
                The kafka broker instance type. See https://aws.amazon.com/msk/pricing/
              title: Class
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 7
        storage:
          title: Storage
          type: object
          description: |
            Specify the storage resources.
          default:
            size: 20480
          properties:
            size:
              default: 20480
              description: |
                The size of the kafka broker storage in MB.
              title: Size
              type: number
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 8
      x-walrus-ui:
        groupOrder:
        - Basic
